// Generated from pinned Rails-1a02651ac37f Mime::LOOKUP in once-campfire7197fff46e15.
namespace Campfire.Features.Integrations;
internal static class RailsMime {
  public static (string Type,string Symbol) Lookup(string type) => type switch {
    "text/html" => ("text/html","html"),
    "application/xhtml+xml" => ("text/html","html"),
    "text/plain" => ("text/plain","text"),
    "text/javascript" => ("text/javascript","js"),
    "application/javascript" => ("text/javascript","js"),
    "application/x-javascript" => ("text/javascript","js"),
    "text/css" => ("text/css","css"),
    "text/calendar" => ("text/calendar","ics"),
    "text/csv" => ("text/csv","csv"),
    "text/vcard" => ("text/vcard","vcf"),
    "text/vtt" => ("text/vtt","vtt"),
    "vtt" => ("text/vtt","vtt"),
    "text/markdown" => ("text/markdown","md"),
    "image/png" => ("image/png","png"),
    "image/jpeg" => ("image/jpeg","jpeg"),
    "image/gif" => ("image/gif","gif"),
    "image/bmp" => ("image/bmp","bmp"),
    "image/tiff" => ("image/tiff","tiff"),
    "image/svg+xml" => ("image/svg+xml","svg"),
    "image/webp" => ("image/webp","webp"),
    "video/mpeg" => ("video/mpeg","mpeg"),
    "audio/mpeg" => ("audio/mpeg","mp3"),
    "audio/ogg" => ("audio/ogg","ogg"),
    "audio/aac" => ("audio/aac","m4a"),
    "audio/mp4" => ("audio/aac","m4a"),
    "video/webm" => ("video/webm","webm"),
    "video/mp4" => ("video/mp4","mp4"),
    "font/otf" => ("font/otf","otf"),
    "font/ttf" => ("font/ttf","ttf"),
    "font/woff" => ("font/woff","woff"),
    "font/woff2" => ("font/woff2","woff2"),
    "application/xml" => ("application/xml","xml"),
    "text/xml" => ("application/xml","xml"),
    "application/x-xml" => ("application/xml","xml"),
    "application/rss+xml" => ("application/rss+xml","rss"),
    "application/atom+xml" => ("application/atom+xml","atom"),
    "application/x-yaml" => ("application/x-yaml","yaml"),
    "text/yaml" => ("application/x-yaml","yaml"),
    "multipart/form-data" => ("multipart/form-data","multipart_form"),
    "application/x-www-form-urlencoded" => ("application/x-www-form-urlencoded","url_encoded_form"),
    "application/json" => ("application/json","json"),
    "text/x-json" => ("application/json","json"),
    "application/jsonrequest" => ("application/json","json"),
    "application/problem+json" => ("application/json","json"),
    "application/pdf" => ("application/pdf","pdf"),
    "application/zip" => ("application/zip","zip"),
    "application/gzip" => ("application/gzip","gzip"),
    "application/x-gzip" => ("application/gzip","gzip"),
    _ => (type,""),
  };
}
