namespace Campfire.Features.Chat;
internal static class SoundCatalog
{
    internal sealed record Sound(string? Text, string? Image, int Width, int Height);
    public static readonly Dictionary<string, Sound> Values = new()
    {
        ["56k"] = new(null, "56k.webp", 79, 33),
        ["bell"] = new("🔔", null, 0, 0),
        ["bezos"] = new("😆💭", null, 0, 0),
        ["bueller"] = new("anyone?", null, 0, 0),
        ["butts"] = new("👐 🚬", null, 0, 0),
        ["clowntown"] = new(null, "clowntown.webp", 210, 150),
        ["cottoneyejoe"] = new("🎶🙉🎶 ", null, 0, 0),
        ["crickets"] = new("hears crickets chirping", null, 0, 0),
        ["curb"] = new(null, "curb.webp", 150, 101),
        ["dadgummit"] = new("dad gummit!! 🎣", null, 0, 0),
        ["dangerzone"] = new(null, "dangerzone.webp", 157, 32),
        ["danielsan"] = new("🎆 🏆 🎆", null, 0, 0),
        ["deeper"] = new(null, "top.webp", 188, 80),
        ["ballmer"] = new("developers!", null, 0, 0),
        ["donotwant"] = new(null, "donotwant.webp", 150, 150),
        ["drama"] = new(null, "drama.webp", 300, 16),
        ["flawless"] = new("#flawless", null, 0, 0),
        ["glados"] = new("🤖💢", null, 0, 0),
        ["gogogo"] = new("Go, go, go!", null, 0, 0),
        ["greatjob"] = new(null, "greatjob.webp", 79, 16),
        ["greyjoy"] = new("😖🎺", null, 0, 0),
        ["guarantee"] = new("guarantees it 👌", null, 0, 0),
        ["heygirl"] = new("✨💁✨", null, 0, 0),
        ["honk"] = new("HONK", null, 0, 0),
        ["horn"] = new("🐶 ✂️ 🐱", null, 0, 0),
        ["horror"] = new("💀 💀 💀 💀 💀 💀 💀", null, 0, 0),
        ["inconceivable"] = new("doesn't think it means what you think it means…", null, 0, 0),
        ["letitgo"] = new("❄️👩❄️⛄️❄️", null, 0, 0),
        ["live"] = new("is DOING IT LIVE", null, 0, 0),
        ["loggins"] = new(null, "loggins.webp", 200, 151),
        ["makeitso"] = new("make it so 👉", null, 0, 0),
        ["noooo"] = new("👸💀😒", null, 0, 0),
        ["nyan"] = new(null, "nyan.webp", 36, 15),
        ["ohmy"] = new("raises an eyebrow 😏", null, 0, 0),
        ["ohyeah"] = new("isn't playing by the rules", null, 0, 0),
        ["pushit"] = new(null, "pushit.webp", 104, 15),
        ["rimshot"] = new("plays a rimshot", null, 0, 0),
        ["rollout"] = new("is rolling out 🚗", null, 0, 0),
        ["rumble"] = new(null, "rumble.webp", 220, 150),
        ["sax"] = new("🌇🎷🎶", null, 0, 0),
        ["secret"] = new("found a secret area 🔑", null, 0, 0),
        ["sexyback"] = new("🔞", null, 0, 0),
        ["story"] = new("and now you know…", null, 0, 0),
        ["tada"] = new("plays a fanfare 🎏", null, 0, 0),
        ["tmyk"] = new("✨ ⭐️ The More You Know ✨ ⭐️", null, 0, 0),
        ["totes"] = new("😁👍", null, 0, 0),
        ["trololo"] = new("трололо", null, 0, 0),
        ["trombone"] = new("plays a sad trombone", null, 0, 0),
        ["unix"] = new("knows this 💻", null, 0, 0),
        ["vuvuzela"] = new("======<() ~ ♪ ~♫", null, 0, 0),
        ["what"] = new(null, "what.webp", 100, 131),
        ["whoomp"] = new("👏‼️😎", null, 0, 0),
        ["wups"] = new("wups!", null, 0, 0),
        ["yay"] = new(null, "yay.webp", 103, 50),
        ["yeah"] = new(null, "yeah.webp", 104, 15),
        ["yodel"] = new("📣🗻🙉", null, 0, 0),
    };
}
